from __future__ import annotations

import argparse
import csv
import json
import sqlite3
import threading
import time
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlparse

POINT_GRID: tuple[tuple[int, int, int], tuple[int, int, int], tuple[int, int, int]] = (
    (15, 10, 15),
    (10, 5, 10),
    (5, 0, 5),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Local score bridge: ingest run.py hits.csv, store in SQLite, "
            "serve Unity-friendly JSON API + simple 3x3 manual correction UI."
        )
    )
    parser.add_argument("--hits-csv", default="data/logs/hits.csv", help="Input hits log generated by run.py")
    parser.add_argument("--db", default="data/logs/score_bridge.db", help="SQLite DB path")
    parser.add_argument("--host", default="127.0.0.1", help="Bind host")
    parser.add_argument("--port", type=int, default=8765, help="Bind port")
    parser.add_argument("--poll-seconds", type=float, default=0.35, help="CSV polling interval")
    parser.add_argument("--history-limit", type=int, default=60, help="Default number of latest hits in API/UI")
    return parser.parse_args()


def _to_int(value: Any, default: int = 0) -> int:
    try:
        return int(float(value))
    except Exception:
        return int(default)


def _to_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except Exception:
        return float(default)


def _clamp01(value: float) -> float:
    return max(0.0, min(1.0, float(value)))


def points_from_norm(norm_x: float, norm_y: float) -> tuple[int, int, int]:
    nx = _clamp01(norm_x)
    ny = _clamp01(norm_y)
    col = min(2, int(nx * 3.0))
    row = min(2, int(ny * 3.0))
    return POINT_GRID[row][col], row, col


def _parse_hit_csv_row(row: dict[str, Any]) -> dict[str, Any]:
    """
    Parse one hits.csv row while supporting both known layouts:

    1) Legacy header (no event_type):
       utc_timestamp,frame,pixel_x,pixel_y,norm_x,norm_y,meter_x,meter_y,speed_before_px_s,speed_after_px_s,angle_change_deg

    2) Current writer rows (event_type inserted after frame), sometimes appended
       into files that still have the legacy header.

    When layout (2) is read with legacy headers, fields shift by one column.
    Detect and unshift that row so scoring uses true norm_x/norm_y.
    """
    event_type = str(row.get("event_type", "") or "").strip().lower()
    pixel_x_token = str(row.get("pixel_x", "") or "").strip().lower()
    shifted_row = not event_type and pixel_x_token in {"entry", "impact", "manual", "unknown"}
    extras = row.get(None) or []

    if shifted_row:
        # Legacy header reading a newer row:
        # pixel_x=event_type, pixel_y=pixel_x, norm_x=pixel_y, ...
        # angle_change lives in the first extras column (if present).
        return {
            "utc_timestamp": str(row.get("utc_timestamp", "")).strip(),
            "frame": _to_int(row.get("frame", 0)),
            "event_type": pixel_x_token or "entry",
            "pixel_x": _to_int(row.get("pixel_y", 0)),
            "pixel_y": _to_int(row.get("norm_x", 0)),
            "norm_x": _to_float(row.get("norm_y", 0.0)),
            "norm_y": _to_float(row.get("meter_x", 0.0)),
            "meter_x": _to_float(row.get("meter_y", 0.0)),
            "meter_y": _to_float(row.get("speed_before_px_s", 0.0)),
            "speed_before_px_s": _to_float(row.get("speed_after_px_s", 0.0)),
            "speed_after_px_s": _to_float(row.get("angle_change_deg", 0.0)),
            "angle_change_deg": _to_float(extras[0], 0.0) if extras else 0.0,
        }

    return {
        "utc_timestamp": str(row.get("utc_timestamp", "")).strip(),
        "frame": _to_int(row.get("frame", 0)),
        "event_type": event_type or "entry",
        "pixel_x": _to_int(row.get("pixel_x", 0)),
        "pixel_y": _to_int(row.get("pixel_y", 0)),
        "norm_x": _to_float(row.get("norm_x", 0.0)),
        "norm_y": _to_float(row.get("norm_y", 0.0)),
        "meter_x": _to_float(row.get("meter_x", 0.0)),
        "meter_y": _to_float(row.get("meter_y", 0.0)),
        "speed_before_px_s": _to_float(row.get("speed_before_px_s", 0.0)),
        "speed_after_px_s": _to_float(row.get("speed_after_px_s", 0.0)),
        "angle_change_deg": _to_float(row.get("angle_change_deg", 0.0)),
    }


class ScoreBridgeStore:
    def __init__(self, db_path: Path, hits_csv: Path):
        self.db_path = db_path
        self.hits_csv = hits_csv
        self._lock = threading.Lock()
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._conn = sqlite3.connect(str(self.db_path), check_same_thread=False)
        self._conn.row_factory = sqlite3.Row
        self._init_db()

    def _init_db(self) -> None:
        with self._conn:
            self._conn.execute(
                """
                CREATE TABLE IF NOT EXISTS hits (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    utc_timestamp TEXT NOT NULL,
                    frame INTEGER NOT NULL,
                    event_type TEXT NOT NULL,
                    pixel_x INTEGER NOT NULL,
                    pixel_y INTEGER NOT NULL,
                    norm_x REAL NOT NULL,
                    norm_y REAL NOT NULL,
                    meter_x REAL NOT NULL,
                    meter_y REAL NOT NULL,
                    auto_points INTEGER NOT NULL,
                    manual_points INTEGER,
                    row_index INTEGER NOT NULL,
                    col_index INTEGER NOT NULL,
                    created_utc TEXT NOT NULL,
                    UNIQUE(utc_timestamp, frame, event_type)
                )
                """
            )
            self._conn.execute(
                """
                CREATE TABLE IF NOT EXISTS meta (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                )
                """
            )
            self._conn.execute(
                """
                CREATE TABLE IF NOT EXISTS unity_events (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    event_type TEXT NOT NULL,
                    player_name TEXT NOT NULL,
                    shot_number INTEGER,
                    running_total INTEGER,
                    total_points INTEGER,
                    utc_timestamp TEXT,
                    created_utc TEXT NOT NULL
                )
                """
            )

    def _get_meta_int(self, key: str, default: int) -> int:
        row = self._conn.execute("SELECT value FROM meta WHERE key = ?", (key,)).fetchone()
        if row is None:
            return int(default)
        return _to_int(row["value"], default)

    def _set_meta_int(self, key: str, value: int) -> None:
        self._conn.execute(
            "INSERT INTO meta(key, value) VALUES(?, ?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",
            (key, str(int(value))),
        )

    def poll_hits_csv(self) -> int:
        if not self.hits_csv.exists():
            return 0

        with self._lock:
            inserted = 0
            with self.hits_csv.open("r", encoding="utf-8", newline="") as handle:
                reader = csv.DictReader(handle)
                rows = list(reader)

            current_line_count = len(rows)
            last_line_count = self._get_meta_int("csv_line_count", 0)
            if current_line_count < last_line_count:
                last_line_count = 0

            now_utc = datetime.now(tz=timezone.utc).isoformat()
            for idx, row in enumerate(rows, start=1):
                if idx <= last_line_count:
                    continue
                parsed = _parse_hit_csv_row(row)
                norm_x = float(parsed["norm_x"])
                norm_y = float(parsed["norm_y"])
                event_type = str(parsed["event_type"]).strip() or "entry"
                auto_points, grid_row, grid_col = points_from_norm(norm_x, norm_y)
                if event_type.lower() == "miss":
                    auto_points = 0
                payload = (
                    str(parsed["utc_timestamp"]),
                    int(parsed["frame"]),
                    event_type,
                    int(parsed["pixel_x"]),
                    int(parsed["pixel_y"]),
                    norm_x,
                    norm_y,
                    float(parsed["meter_x"]),
                    float(parsed["meter_y"]),
                    int(auto_points),
                    int(grid_row),
                    int(grid_col),
                    now_utc,
                )
                cur = self._conn.execute(
                    """
                    INSERT OR IGNORE INTO hits(
                        utc_timestamp, frame, event_type, pixel_x, pixel_y, norm_x, norm_y,
                        meter_x, meter_y, auto_points, row_index, col_index, created_utc
                    )
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    payload,
                )
                if cur.rowcount > 0:
                    inserted += 1

            self._set_meta_int("csv_line_count", current_line_count)
            self._conn.commit()
            return inserted

    def set_manual_points(self, hit_id: int, points: int | None) -> bool:
        with self._lock:
            cur = self._conn.execute(
                "UPDATE hits SET manual_points = ? WHERE id = ?",
                (points, int(hit_id)),
            )
            self._conn.commit()
            return cur.rowcount > 0

    def list_hits(self, *, limit: int, since_id: int = 0) -> list[dict[str, Any]]:
        with self._lock:
            rows = self._conn.execute(
                """
                SELECT id, utc_timestamp, frame, event_type, pixel_x, pixel_y, norm_x, norm_y,
                       meter_x, meter_y, auto_points, manual_points, row_index, col_index, created_utc
                FROM hits
                WHERE id > ?
                ORDER BY id DESC
                LIMIT ?
                """,
                (int(since_id), max(1, int(limit))),
            ).fetchall()
        result: list[dict[str, Any]] = []
        for r in rows:
            manual_points = r["manual_points"]
            points = int(manual_points) if manual_points is not None else int(r["auto_points"])
            result.append(
                {
                    "id": int(r["id"]),
                    "utc_timestamp": r["utc_timestamp"],
                    "frame": int(r["frame"]),
                    "event_type": r["event_type"],
                    "pixel_x": int(r["pixel_x"]),
                    "pixel_y": int(r["pixel_y"]),
                    "norm_x": float(r["norm_x"]),
                    "norm_y": float(r["norm_y"]),
                    "meter_x": float(r["meter_x"]),
                    "meter_y": float(r["meter_y"]),
                    "auto_points": int(r["auto_points"]),
                    "manual_points": int(manual_points) if manual_points is not None else None,
                    "points": points,
                    "corrected": manual_points is not None,
                    "grid_row": int(r["row_index"]),
                    "grid_col": int(r["col_index"]),
                    "created_utc": r["created_utc"],
                }
            )
        return result

    def total_points(self) -> int:
        with self._lock:
            row = self._conn.execute(
                "SELECT COALESCE(SUM(COALESCE(manual_points, auto_points)), 0) AS total FROM hits"
            ).fetchone()
        return int(row["total"] if row is not None else 0)

    def latest_hit(self) -> dict[str, Any] | None:
        hits = self.list_hits(limit=1, since_id=0)
        return hits[0] if hits else None

    def record_unity_event(
        self,
        *,
        event_type: str,
        player_name: str,
        shot_number: int | None = None,
        running_total: int | None = None,
        total_points: int | None = None,
        utc_timestamp: str = "",
    ) -> None:
        clean_name = str(player_name).strip() or "Player"
        clean_event = str(event_type).strip() or "unknown"
        now_utc = datetime.now(tz=timezone.utc).isoformat()
        with self._lock:
            self._conn.execute(
                """
                INSERT INTO unity_events(
                    event_type, player_name, shot_number, running_total, total_points, utc_timestamp, created_utc
                )
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    clean_event,
                    clean_name,
                    int(shot_number) if shot_number is not None else None,
                    int(running_total) if running_total is not None else None,
                    int(total_points) if total_points is not None else None,
                    str(utc_timestamp or "").strip(),
                    now_utc,
                ),
            )
            self._conn.commit()

    def latest_registered_player_event(self) -> tuple[int, str] | None:
        with self._lock:
            row = self._conn.execute(
                """
                SELECT id, player_name
                FROM unity_events
                WHERE event_type = 'player_registered'
                ORDER BY id DESC
                LIMIT 1
                """
            ).fetchone()
        if row is None:
            return None
        return int(row["id"]), str(row["player_name"])

    def create_manual_hit(
        self,
        *,
        points: int,
        player_name: str = "",
        event_type: str = "manual",
        utc_timestamp: str = "",
    ) -> dict[str, Any]:
        safe_points = int(points)
        clean_event_type = str(event_type).strip() or "manual"
        clean_name = str(player_name).strip() or "Manual"
        ts = str(utc_timestamp).strip() or datetime.now(tz=timezone.utc).isoformat()
        now_utc = datetime.now(tz=timezone.utc).isoformat()

        # Approximate placement in the 3x3 grid when only points are provided.
        if safe_points >= 15:
            row_index, col_index = 0, 0
        elif safe_points >= 10:
            row_index, col_index = 0, 1
        elif safe_points >= 5:
            row_index, col_index = 1, 1
        else:
            row_index, col_index = 2, 1

        norm_x = (float(col_index) + 0.5) / 3.0
        norm_y = (float(row_index) + 0.5) / 3.0
        frame = int(time.time() * 1000.0)

        with self._lock:
            cur = self._conn.execute(
                """
                INSERT INTO hits(
                    utc_timestamp, frame, event_type, pixel_x, pixel_y, norm_x, norm_y,
                    meter_x, meter_y, auto_points, manual_points, row_index, col_index, created_utc
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    ts,
                    frame,
                    clean_event_type,
                    0,
                    0,
                    norm_x,
                    norm_y,
                    0.0,
                    0.0,
                    safe_points,
                    safe_points,
                    row_index,
                    col_index,
                    now_utc,
                ),
            )
            self._conn.execute(
                """
                INSERT INTO unity_events(
                    event_type, player_name, shot_number, running_total, total_points, utc_timestamp, created_utc
                )
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    "manual_hit_created",
                    clean_name,
                    None,
                    None,
                    safe_points,
                    ts,
                    now_utc,
                ),
            )
            hit_id = int(cur.lastrowid)
            row = self._conn.execute(
                """
                SELECT id, utc_timestamp, frame, event_type, pixel_x, pixel_y, norm_x, norm_y,
                       meter_x, meter_y, auto_points, manual_points, row_index, col_index, created_utc
                FROM hits
                WHERE id = ?
                """,
                (hit_id,),
            ).fetchone()
            self._conn.commit()

        if row is None:
            return {"id": hit_id, "points": safe_points}

        return {
            "id": int(row["id"]),
            "utc_timestamp": row["utc_timestamp"],
            "frame": int(row["frame"]),
            "event_type": row["event_type"],
            "pixel_x": int(row["pixel_x"]),
            "pixel_y": int(row["pixel_y"]),
            "norm_x": float(row["norm_x"]),
            "norm_y": float(row["norm_y"]),
            "meter_x": float(row["meter_x"]),
            "meter_y": float(row["meter_y"]),
            "auto_points": int(row["auto_points"]),
            "manual_points": int(row["manual_points"]) if row["manual_points"] is not None else None,
            "points": int(row["manual_points"]) if row["manual_points"] is not None else int(row["auto_points"]),
            "corrected": row["manual_points"] is not None,
            "grid_row": int(row["row_index"]),
            "grid_col": int(row["col_index"]),
            "created_utc": row["created_utc"],
        }

    def leaderboard_top(self, *, limit: int = 3) -> list[dict[str, Any]]:
        safe_limit = max(1, int(limit))
        with self._lock:
            rows = self._conn.execute(
                """
                SELECT id, player_name, total_points, created_utc
                FROM unity_events
                WHERE event_type = 'turn_completed'
                ORDER BY id ASC
                """
            ).fetchall()

        best_by_player_key: dict[str, dict[str, Any]] = {}
        for row in rows:
            raw_name = str(row["player_name"]).strip() or "Player"
            key = raw_name.casefold()
            candidate = {
                "id": int(row["id"]),
                "player_name": raw_name,
                "points": int(row["total_points"] if row["total_points"] is not None else 0),
                "created_utc": str(row["created_utc"] or ""),
            }

            existing = best_by_player_key.get(key)
            if existing is None:
                best_by_player_key[key] = candidate
                continue

            if candidate["points"] > existing["points"]:
                best_by_player_key[key] = candidate
                continue

            if candidate["points"] == existing["points"] and candidate["id"] < existing["id"]:
                best_by_player_key[key] = candidate

        leaderboard = sorted(
            best_by_player_key.values(),
            key=lambda item: (-int(item["points"]), int(item["id"])),
        )[:safe_limit]

        output: list[dict[str, Any]] = []
        for index, item in enumerate(leaderboard, start=1):
            output.append(
                {
                    "rank": index,
                    "player_name": str(item["player_name"]),
                    "points": int(item["points"]),
                    "source_event_id": int(item["id"]),
                    "created_utc": str(item["created_utc"]),
                }
            )
        return output


def create_handler(store: ScoreBridgeStore, history_limit: int):
    class Handler(BaseHTTPRequestHandler):
        def _send(self, status: int, body: bytes, content_type: str) -> None:
            self.send_response(status)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Access-Control-Allow-Headers", "Content-Type")
            self.send_header("Access-Control-Allow-Methods", "GET,POST,OPTIONS")
            self.end_headers()
            self.wfile.write(body)

        def _send_json(self, payload: dict[str, Any], status: int = 200) -> None:
            self._send(status, json.dumps(payload).encode("utf-8"), "application/json; charset=utf-8")

        def _read_json_body(self) -> dict[str, Any] | None:
            raw_length = self.headers.get("Content-Length", "0")
            body_len = _to_int(raw_length, 0)
            raw = self.rfile.read(max(0, body_len))
            try:
                return json.loads(raw.decode("utf-8")) if raw else {}
            except Exception:
                self._send_json({"ok": False, "error": "invalid_json"}, status=400)
                return None

        def do_OPTIONS(self) -> None:
            self._send(204, b"", "text/plain")

        def do_GET(self) -> None:
            parsed = urlparse(self.path)
            path = parsed.path
            qs = parse_qs(parsed.query)

            if path == "/":
                self._send(200, UI_HTML.encode("utf-8"), "text/html; charset=utf-8")
                return

            if path == "/api/state":
                limit = _to_int((qs.get("limit", [str(history_limit)])[0]), history_limit)
                hits = store.list_hits(limit=limit, since_id=0)
                active_player_event = store.latest_registered_player_event()
                payload = {
                    "ok": True,
                    "total_points": store.total_points(),
                    "active_player": active_player_event[1] if active_player_event is not None else None,
                    "active_player_event_id": active_player_event[0] if active_player_event is not None else 0,
                    "latest_hit": hits[0] if hits else None,
                    "hits": hits,
                    "grid": POINT_GRID,
                }
                self._send_json(payload)
                return

            if path == "/api/hits":
                limit = _to_int((qs.get("limit", [str(history_limit)])[0]), history_limit)
                since_id = _to_int((qs.get("since_id", ["0"])[0]), 0)
                payload = {
                    "ok": True,
                    "hits": store.list_hits(limit=limit, since_id=since_id),
                }
                self._send_json(payload)
                return

            if path == "/api/leaderboard":
                limit = _to_int((qs.get("limit", ["3"])[0]), 3)
                payload = {
                    "ok": True,
                    "leaderboard": store.leaderboard_top(limit=limit),
                }
                self._send_json(payload)
                return

            self._send_json({"ok": False, "error": "not_found"}, status=404)

        def do_POST(self) -> None:
            parsed = urlparse(self.path)
            path = parsed.path

            if path == "/api/hits/manual":
                payload = self._read_json_body()
                if payload is None:
                    return
                points = _to_int(payload.get("points", -1), -1)
                if points not in {0, 5, 10, 15}:
                    self._send_json({"ok": False, "error": "points_must_be_one_of_0_5_10_15"}, status=400)
                    return
                hit = store.create_manual_hit(
                    points=points,
                    player_name=str(payload.get("player_name", "")).strip(),
                    event_type=str(payload.get("event_type", "manual")).strip() or "manual",
                    utc_timestamp=str(payload.get("utc_timestamp", "")).strip(),
                )
                self._send_json({"ok": True, "hit": hit})
                return

            if path == "/api/player/register":
                payload = self._read_json_body()
                if payload is None:
                    return
                player_name = str(payload.get("player_name", "")).strip()
                if not player_name:
                    self._send_json({"ok": False, "error": "player_name_required"}, status=400)
                    return
                store.record_unity_event(
                    event_type="player_registered",
                    player_name=player_name,
                    utc_timestamp=str(payload.get("utc_timestamp", "")).strip(),
                )
                self._send_json({"ok": True})
                return

            if path == "/api/turn/shot":
                payload = self._read_json_body()
                if payload is None:
                    return
                player_name = str(payload.get("player_name", "")).strip()
                if not player_name:
                    self._send_json({"ok": False, "error": "player_name_required"}, status=400)
                    return
                store.record_unity_event(
                    event_type="shot_registered",
                    player_name=player_name,
                    shot_number=_to_int(payload.get("shot_number", 0), 0),
                    running_total=_to_int(payload.get("running_total", 0), 0),
                    utc_timestamp=str(payload.get("utc_timestamp", "")).strip(),
                )
                self._send_json({"ok": True})
                return

            if path == "/api/turn/complete":
                payload = self._read_json_body()
                if payload is None:
                    return
                player_name = str(payload.get("player_name", "")).strip()
                if not player_name:
                    self._send_json({"ok": False, "error": "player_name_required"}, status=400)
                    return
                store.record_unity_event(
                    event_type="turn_completed",
                    player_name=player_name,
                    total_points=_to_int(payload.get("total_points", 0), 0),
                    utc_timestamp=str(payload.get("utc_timestamp", "")).strip(),
                )
                self._send_json({"ok": True})
                return

            parts = [p for p in parsed.path.strip("/").split("/") if p]
            if len(parts) != 4 or parts[0] != "api" or parts[1] != "hits":
                self._send_json({"ok": False, "error": "not_found"}, status=404)
                return

            hit_id = _to_int(parts[2], -1)
            if hit_id <= 0:
                self._send_json({"ok": False, "error": "invalid_hit_id"}, status=400)
                return

            if parts[3] == "score":
                payload = self._read_json_body()
                if payload is None:
                    return
                points = _to_int(payload.get("points", -1), -1)
                if points not in {0, 5, 10, 15}:
                    self._send_json({"ok": False, "error": "points_must_be_one_of_0_5_10_15"}, status=400)
                    return
                ok = store.set_manual_points(hit_id, points)
                if not ok:
                    self._send_json({"ok": False, "error": "hit_not_found"}, status=404)
                    return
                self._send_json({"ok": True})
                return

            if parts[3] == "clear":
                ok = store.set_manual_points(hit_id, None)
                if not ok:
                    self._send_json({"ok": False, "error": "hit_not_found"}, status=404)
                    return
                self._send_json({"ok": True})
                return

            self._send_json({"ok": False, "error": "not_found"}, status=404)

        def log_message(self, format: str, *args: Any) -> None:
            return

    return Handler


def poll_loop(store: ScoreBridgeStore, poll_seconds: float, stop_event: threading.Event) -> None:
    interval = max(0.10, float(poll_seconds))
    while not stop_event.is_set():
        try:
            inserted = store.poll_hits_csv()
            if inserted > 0:
                print(f"[ScoreBridge] imported_hits={inserted}")
        except Exception as exc:
            print(f"[ScoreBridge] poll_error={exc}")
        stop_event.wait(interval)


UI_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Goal Score Bridge</title>
  <style>
    body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: #101216; color: #e9eef8; }
    .wrap { max-width: 1120px; margin: 0 auto; padding: 20px; }
    .top { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 14px; }
    .card { background: #1b2029; border: 1px solid #2a313d; border-radius: 12px; padding: 14px; }
    .k { color: #9fb0c8; font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; }
    .v { font-size: 30px; font-weight: 700; margin-top: 4px; }
    .grid { display: grid; grid-template-columns: repeat(3, minmax(60px, 90px)); gap: 8px; margin-top: 12px; }
    .grid button { height: 58px; border: 0; border-radius: 10px; background: #2d66f6; color: #fff; font-size: 22px; font-weight: 700; cursor: pointer; }
    .grid button:hover { background: #3a74ff; }
    .row { display: grid; grid-template-columns: 64px 1fr 80px 88px 96px; gap: 8px; align-items: center; font-size: 13px; border-top: 1px solid #2a313d; padding: 8px 0; }
    .row:first-child { border-top: 0; }
    .chip { padding: 3px 8px; border-radius: 999px; font-size: 12px; display: inline-block; }
    .chip.entry { background: #1f7f5d; color: #ddfff2; }
    .chip.impact { background: #8a2f4f; color: #ffe2ec; }
    .sel { outline: 2px solid #4e8cff; border-radius: 8px; }
    .btn { margin-top: 10px; height: 36px; border: 1px solid #3c4657; background: #202734; color: #d9e3f6; border-radius: 8px; cursor: pointer; }
  </style>
</head>
<body>
  <div class="wrap">
    <div class="top">
      <div class="card">
        <div class="k">Total Points</div>
        <div id="totalPoints" class="v">0</div>
      </div>
      <div class="card">
        <div class="k">Selected Hit</div>
        <div id="selectedInfo" style="margin-top:8px;font-size:14px;">No hit selected</div>
        <div class="grid" id="scoreGrid"></div>
        <button class="btn" id="clearBtn" type="button">Clear Manual Override</button>
      </div>
    </div>
    <div class="card">
      <div class="k">Recent Hits (Latest First)</div>
      <div id="rows"></div>
    </div>
  </div>
  <script>
    const GRID = [[15,10,15],[10,5,10],[5,0,5]];
    let selectedId = null;
    let currentHits = [];

    function esc(s) {
      return String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
    }

    async function api(path, opts={}) {
      const r = await fetch(path, opts);
      const j = await r.json();
      if (!r.ok || !j.ok) throw new Error(j.error || "request_failed");
      return j;
    }

    function renderGrid() {
      const root = document.getElementById("scoreGrid");
      root.innerHTML = "";
      for (const row of GRID) {
        for (const value of row) {
          const b = document.createElement("button");
          b.textContent = String(value);
          b.onclick = () => setScore(value);
          root.appendChild(b);
        }
      }
    }

    function selectedHit() {
      return currentHits.find(h => h.id === selectedId) || null;
    }

    function renderSelected() {
      const hit = selectedHit();
      const el = document.getElementById("selectedInfo");
      if (!hit) {
        el.textContent = "No hit selected";
        return;
      }
      const mode = hit.corrected ? "manual" : "auto";
      el.innerHTML =
        `ID ${hit.id} | points <b>${hit.points}</b> (${mode})<br/>` +
        `norm=(${hit.norm_x.toFixed(3)}, ${hit.norm_y.toFixed(3)})` +
        ` frame=${hit.frame} type=${esc(hit.event_type)}`;
    }

    function renderRows() {
      const root = document.getElementById("rows");
      root.innerHTML = "";
      for (const h of currentHits) {
        const row = document.createElement("div");
        row.className = "row" + (h.id === selectedId ? " sel" : "");
        row.onclick = () => { selectedId = h.id; renderRows(); renderSelected(); };
        const ts = new Date(h.utc_timestamp);
        const hh = Number.isNaN(ts.getTime()) ? h.utc_timestamp : ts.toLocaleTimeString();
        row.innerHTML =
          `<div>#${h.id}</div>` +
          `<div>${hh} <span class="chip ${esc(h.event_type)}">${esc(h.event_type)}</span></div>` +
          `<div>(${h.norm_x.toFixed(2)}, ${h.norm_y.toFixed(2)})</div>` +
          `<div>${h.corrected ? "manual" : "auto"}</div>` +
          `<div><b>${h.points}</b> pts</div>`;
        root.appendChild(row);
      }
    }

    async function setScore(points) {
      if (!selectedId) return;
      await api(`/api/hits/${selectedId}/score`, {
        method: "POST",
        headers: {"Content-Type":"application/json"},
        body: JSON.stringify({points})
      });
      await refresh();
    }

    async function clearScore() {
      if (!selectedId) return;
      await api(`/api/hits/${selectedId}/clear`, {method: "POST"});
      await refresh();
    }

    async function refresh() {
      const state = await api("/api/state?limit=60");
      document.getElementById("totalPoints").textContent = String(state.total_points);
      currentHits = state.hits || [];
      if (!selectedId && currentHits.length > 0) selectedId = currentHits[0].id;
      if (selectedId && !currentHits.some(h => h.id === selectedId) && currentHits.length > 0) {
        selectedId = currentHits[0].id;
      }
      renderRows();
      renderSelected();
    }

    document.getElementById("clearBtn").onclick = () => clearScore().catch(console.error);
    renderGrid();
    refresh().catch(console.error);
    setInterval(() => refresh().catch(console.error), 450);
  </script>
</body>
</html>
"""


def main() -> None:
    args = parse_args()
    hits_csv = Path(args.hits_csv)
    db_path = Path(args.db)
    store = ScoreBridgeStore(db_path=db_path, hits_csv=hits_csv)

    stop_event = threading.Event()
    poller = threading.Thread(
        target=poll_loop,
        args=(store, float(args.poll_seconds), stop_event),
        daemon=True,
    )
    poller.start()

    handler = create_handler(store, int(args.history_limit))
    server = ThreadingHTTPServer((str(args.host), int(args.port)), handler)
    print(f"[ScoreBridge] hits_csv={hits_csv.resolve()}")
    print(f"[ScoreBridge] db={db_path.resolve()}")
    print(f"[ScoreBridge] ui=http://{args.host}:{args.port}/")
    print("[ScoreBridge] Unity poll endpoint: GET /api/state")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        stop_event.set()
        server.server_close()


if __name__ == "__main__":
    main()
